Fix the printing of std::string
- Debug function expects to get c-style
  string.
- Fixes a following error:

rocm-systems/projects/clr/rocclr/os/os_posix.cpp:1013:71:
error: cannot pass object of non-trivial type 'const std::string'
(aka 'const basic_string<char>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
1013 |     ClPrint(amd::LOG_DEBUG, amd::LOG_RESOURCE, "%s cannot be opened", path);
[hip-clr] rocm-systems/projects/clr/rocclr/os/os_posix.cpp:1013:71:
error: cannot pass object of non-trivial type 'const std::string' (aka 'const basic_string<char>')
through variadic function; call will abort at runtime [-Wnon-pod-varargs]

Signed-off-by: Mika Laitio <mika.laitio@amd.com>