fix(hip-tests): Add UnalignedKernelCornerCases entry in memory.yaml
hipMemset_UnalignedKernelCornerCases was added in PR https://github.com/ROCm/rocm-systems/pull/3872,
but was not included in the memory.yaml. Subsequent PRs in rocm-systems are seeing errors in
TheRock build:
ERROR: The following Catch2 test cases have no entry in their YAML config.

Error was reproduced locally via:
cd projects/hip-tests
THEROCK_REQUIRE_HIP_YAML_ENTRIES=1 python3 catch/config/check_sources.py catch/config/configs catch.

Fixes issues introduced in #3872.