mirage hotswap needs to mount relevent files into the container. all mirage system mounts should go under /mnt/mirage
like /mnt/mirage/emulator/hotswap/ for hotswap files

```
ERROR: ld.so: object '/home/arosa/rocm-systems/emulation/mirage/build/hotswap/lib/libhsa-runtime64.so.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/home/arosa/rocm-systems/emulation/mirage/build/hotswap/lib/libhotswap_intercept.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
hello
```