dbgapi/msvc: dbgapi_assert_not_reached
MSVC does not have __builtin_trap, resulting in:

 D:\therock\src\rocm-systems\projects\rocdbgapi\src\queue.h(187): error C3861: '__builtin_trap': identifier not found

... and many more of the same.

Reimplement dbgapi_assert_not_reached using __debugbreak + abort.  Add
the abort to match better the semantics of __builtin_trap, which is
noreturn.  I.e., to avoid someone catching the __debugbreak in a
debugger an then continuing after the trap.

Change-Id: I6f7db2cfed6afa0fbdc8592124196e5f415fd540
commit-id:6c46f3f4