dbgapi/msvc: Fix build error with missing typename
MSVC currently shows this build error:

 D:\therock\src\rocm-systems\projects\rocdbgapi\src\architecture.cpp(7940): error C7510: 'value_type': use of dependent type name must be prefixed with 'typename'
 ... followed by cascading build errors...

Fix it by adding "typename".

Change-Id: I85ccd11e6777fdbc5b24c9f0b484d59a21e4aff4
commit-id:f4d5aea0