Do not require kpack code object to be available for all GPUs
Allow a situation where system has more than one
different type of GPU installed but rocm
has installed the kpack code objects only for some of them.

In this case we do not want to return an error if kpack object
is not found some of the systems. Instead we will load
the kpack code object for all of the gpu types we find.

If application only uses the GPUs for which we have loaded the
kpack object, it will work just fine.

If the application try to use some of the GPUs for which
the kpack object is not available, it will cause error later
on the execution indicating that the objecst are missing in
a following way. That error message could be better but
it's another issue.

Traceback (most recent call last):
  File "/home/butler/bugs/therock_6696/pytorch_cuda_0_test.py", line 7, in <module>
    print(torch.zeros(1, device=f"cuda:{i}"), flush=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.AcceleratorError: CUDA error: invalid kernel file
Search for `hipErrorInvalidKernelFile' in https://rocm.docs.amd.com/projects/HIP/en/latest/index.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Device-side assertion tracking was not enabled by user.

Signed-off-by: Mika Laitio <mika.laitio@amd.com>