rocprofiler-sdk add ROCPROFILER_BUILD_ELFIO option
Add new build flag ROCPROFILER_BUILD_ELFIO which
is by default on to support the current way of building.

When the option is set off, the elfio is tried to find from
the system path instead of downloading it. This allows
therock to install the same elfio version that rocprofiler-sdk
uses and then patch it to support the gcc 15 to fix a following
build error:

therock/build/third-party/elfio/build_elfio/
    dist/include/elfio/elf_types.hpp:30:20:
    error: unknown type name 'uint16_t'
    9.5        30 | using Elf_Half   = uint16_t;

Later the same elfio version may be used also on some other
projects.

fixes for: https://github.com/ROCm/TheRock/issues/3517

Signed-off-by: Mika Laitio <mika.laitio@amd.com>