dbgapi/msvc: Tweak CMakeLists.txt for MSVC
With all the previous patches in place, all that is left to build with
MSVC, is tweaking CMakeLists.txt.  That's what this commit does.

"/GR-" is the equivalent of GCC's -fno-rtti.

"/permissive-" is needed to tell MSVC to enable conforming mode.
Otherwise, we get the following errors:

  D:\therock\src\rocm-systems\projects\rocdbgapi\src\process.cpp(1379): error C2668: 'amd::dbgapi::process_t::range': ambiguous call to overloaded function
  D:\therock\src\rocm-systems\projects\rocdbgapi\src\process.h(384): note: could be 'amd::dbgapi::handle_object_set_t<amd::dbgapi::agent_t>::const_range_t amd::dbgapi::process_t::range<amd::dbgapi::agent_t>(void) const'
  D:\therock\src\rocm-systems\projects\rocdbgapi\src\process.h(379): note: or       'amd::dbgapi::handle_object_set_t<amd::dbgapi::agent_t>::range_t amd::dbgapi::process_t::range<amd::dbgapi::agent_t>(void)'
  D:\therock\src\rocm-systems\projects\rocdbgapi\src\process.cpp(1379): note: while trying to match the argument list '()'
  D:\therock\src\rocm-systems\projects\rocdbgapi\src\process.cpp(1708): error C2668: 'amd::dbgapi::process_t::range': ambiguous call to overloaded function
  D:\therock\src\rocm-systems\projects\rocdbgapi\src\process.h(384): note: could be 'amd::dbgapi::handle_object_set_t<amd::dbgapi::agent_t>::const_range_t amd::dbgapi::process_t::range<amd::dbgapi::agent_t>(void) const'
  D:\therock\src\rocm-systems\projects\rocdbgapi\src\process.h(379): note: or       'amd::dbgapi::handle_object_set_t<amd::dbgapi::agent_t>::range_t amd::dbgapi::process_t::range<amd::dbgapi::agent_t>(void)'
  D:\therock\src\rocm-systems\projects\rocdbgapi\src\process.cpp(1708): note: while trying to match the argument list '()'

Change-Id: Ic89cb00c94b4b6561fa03bcb335d2e283c4036e6
commit-id:33ed315a