fix(rocr): Fix invalid int-to-enum conversion in KFDEvictTest
Initialize HSAKMT_STATUS ret with HSAKMT_STATUS_SUCCESS instead of 0.
Assigning the integer literal 0 to the HSAKMT_STATUS enum is an
ill-formed conversion that GCC rejects by default (-fpermissive),
breaking the kfdtest build. Use the proper enum value instead.

Build error:

  KFDEvictTest.cpp: In member function 'void KFDEvictTest::AllocBuffers(
  bool, HSAuint32, HSAuint32, HSAuint64, std::vector<void*>&)':
  KFDEvictTest.cpp:66:25: error: invalid conversion from 'int' to
  'HSAKMT_STATUS' {aka '_HSAKMT_STATUS'} [-fpermissive]
     66 |     HSAKMT_STATUS ret = 0;
        |                         ^
        |                         |
        |                         int
  make[2]: *** [CMakeFiles/kfdtest.dir/build.make:569:
  CMakeFiles/kfdtest.dir/src/KFDEvictTest.cpp.o] Error 1

Signed-off-by: Yang Su <Yang.Su2@amd.com>