rocdbgapi: hold the address space by pointer in memory_error_t
GCC 16 has -Wsfinae-incomplete enabled by default, which breaks the build
with -Werror:

    [  4%] Building CXX object CMakeFiles/amd-dbgapi.dir/src/agent.cpp.o
    In file included from /home/simark/src/rocm-systems/projects/rocdbgapi/src/agent.h:27,
                     from /home/simark/src/rocm-systems/projects/rocdbgapi/src/agent.cpp:21:
    /home/simark/src/rocm-systems/projects/rocdbgapi/src/memory.h:182:7: error: defining ‘amd::dbgapi::address_space_t’, which previously failed to be complete in a SFINAE context [-Werror=sfinae-incomplete=]
      182 | class address_space_t
          |       ^~~~~~~~~~~~~~~

Compiling with -Wsfinae-incomplete=2 and -Wsystem-headers reveals the
root of the problem:

    In file included from /usr/include/c++/16/bits/move.h:37,
                     from /usr/include/c++/16/bits/exception_ptr.h:41,
                     from /usr/include/c++/16/exception:182,
                     from /usr/include/c++/16/stdexcept:40:
    /usr/include/c++/16/type_traits: In substitution of ‘template<class _Tp, class _Up> using std::__is_assignable_impl = std::__bool_constant<__is_assignable(_Tp, _Up)> [with _Tp = const amd::dbgapi::address_space_t&; _Up = const amd::dbgapi::address_space_
    t&]’:
    /usr/include/c++/16/type_traits:1369:12:   required from ‘struct std::is_copy_assignable<const amd::dbgapi::address_space_t&>’
     1369 |     struct is_copy_assignable
          |            ^~~~~~~~~~~~~~~~~~
    /usr/include/c++/16/type_traits:191:35:   required by substitution of ‘template<class ... _Bn> std::__detail::__first_t<std::integral_constant<bool, true>, typename std::enable_if<(bool)(_Bn::value), void>::type ...> std::__detail::__and_fn(int) [with _B
    n = {std::is_copy_assignable<const amd::dbgapi::address_space_t&>, std::is_copy_assignable<long unsigned int>}]’
      191 |                                       __enable_if_t<bool(_Bn::value)>...>;
          |                                                               ^~~~~
    /usr/include/c++/16/type_traits:207:42:   required from ‘struct std::__and_<std::is_copy_assignable<const amd::dbgapi::address_space_t&>, std::is_copy_assignable<long unsigned int> >’
      207 |     : decltype(__detail::__and_fn<_Bn...>(0))
          |                ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
    /usr/include/c++/16/bits/stl_pair.h:945:38:   required from ‘struct std::pair<const amd::dbgapi::address_space_t&, long unsigned int>’
      945 |                                        is_copy_assignable<_T2>>::value,
          |                                                                  ^~~~~
    /usr/include/c++/16/type_traits:3722:7:   required from ‘constexpr const bool std::is_trivially_copy_constructible_v<std::pair<const amd::dbgapi::address_space_t&, long unsigned int> >’
     3722 |     = __is_trivially_constructible(_Tp, __add_lval_ref_t<const _Tp>);
          |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/include/c++/16/optional:812:11:   required from ‘class std::optional<std::pair<const amd::dbgapi::address_space_t&, long unsigned int> >’
      812 |     class optional
          |           ^~~~~~~~
    /home/simark/src/rocm-systems/projects/rocdbgapi/src/exception.h:88:5:   required from here
       88 |     m_address;
          |     ^~~~~~~~~
    /usr/include/c++/16/type_traits:1355:50: error: failed to complete ‘amd::dbgapi::address_space_t’ in SFINAE context [-Werror=sfinae-incomplete=]
     1355 |     using __is_assignable_impl = __bool_constant<__is_assignable(_Tp, _Up)>;
          |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~

The problem occurs in memory_error_t, when defining:

    std::optional<
      std::pair<const address_space_t &, amd_dbgapi_segment_address_t>>
      m_address;

std::pair uses SFINAE to know if the type `const address_space_t &` is
copy assignable.  Because the type is a reference, and assigning to a
reference is like assigning to the type itself, then it needs to know
whether `address_space_t` is copy-assignable.  But `address_space_t` is
only forward-declared at this point, and becomes fully defined later.  This
is dangerous and this is what GCC warns about.  The SFINAE result can be
different before the definition of the type and after it.

We can't fix it by including "memory.h" in "exception.h", as that would
create a cycle.

We can fix it by moving the definition of `memory_error_t` to "memory.h",
but I suppose we don't want to do that, we want to keep exceptions in
"exceptions.h".

This patch proposes to side-step the issue by switching to a pointer:

    std::optional<
      std::pair<const address_space_t *, amd_dbgapi_segment_address_t>>
      m_address;

There is no fallout to fix, as this field is ultimately not used (the
memory_error_t::address() getter is never called) (which means we could
maybe delete it too...).