dbgapi/msvc: NOMINMAX
When compiling dbgapi standalone (i.e., outside TheRock) with MSVC, we
get this build error:

 D:\therock\src\rocm-systems\projects\rocdbgapi\src\os_driver_kmd.cpp(1310): error C2589: '(': illegal token on right side of '::'
 D:\therock\src\rocm-systems\projects\rocdbgapi\src\os_driver_kmd.cpp(1310): error C3878: syntax error: unexpected token '(' following 'expression'
 D:\therock\src\rocm-systems\projects\rocdbgapi\src\os_driver_kmd.cpp(1310): error C2760: syntax error: ')' was unexpected here; expected ';'
 D:\therock\src\rocm-systems\projects\rocdbgapi\src\os_driver_kmd.cpp(1310): error C3878: syntax error: unexpected token ')' following 'expression-statement'
 D:\therock\src\rocm-systems\projects\rocdbgapi\src\os_driver_kmd.cpp(1310): error C2760: syntax error: ':' was unexpected here; expected ';'
 D:\therock\src\rocm-systems\projects\rocdbgapi\src\os_driver_kmd.cpp(1310): error C3878: syntax error: unexpected token ':' following 'expression-statement'
 D:\therock\src\rocm-systems\projects\rocdbgapi\src\os_driver_kmd.cpp(1384): error C2059: syntax error: ')'
 D:\therock\src\rocm-systems\projects\rocdbgapi\src\os_driver_kmd.cpp(1384): error C2589: '(': illegal token on right side of '::'
 D:\therock\src\rocm-systems\projects\rocdbgapi\src\os_driver_kmd.cpp(1384): error C2672: 'amd::dbgapi::tracer<AMD_DBGAPI_LOG_LEVEL_VERBOSE>::leave': no matching overloaded function found

The problem is that windows.h defines min/max macros, which conflict
with os_driver_kmd.cpp's use of std::min.

Fix this by defining NOMINMAX before including windows.h.

We hadn't seen the need for this before, because:

 - MinGW always defines NOMINMAX.

 - When compiling under TheRock with clang/msvc, TheRock defines
   -DNOMINMAX on the command line.

Change-Id: I42a3f0d24125dfa870fef1715ab6214094017cad
commit-id:8969885c